# Generated by Django 5.1.6 on 2025-02-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Dirección de correo electrónico', max_length=254, unique=True),
        ),
    ]
