# Generated by Django 5.1.6 on 2025-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_cover_book_created_book_description_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cover',
            field=models.URLField(blank=True, default='https://media.briantracy.com/blog/wp-content/uploads/2021/12/03083020/how-to-become-an-author.jpg', help_text='URL de la foto del autor', null=True),
        ),
    ]
