# Generated by Django 5.1.6 on 2025-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_author_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si el autor está marcado como favorito'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si el libro está marcado como favorito'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si la etiqueta está marcada como favorita'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si la cita está marcada como favorita'),
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-is_favorite', 'name'), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-is_favorite', 'title'), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-is_favorite', 'title'), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-is_favorite', 'created', 'title'), 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
    ]
