# Generated by Django 5.1.6 on 2025-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_favorite_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-is_favorite', 'name')},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-is_favorite', 'title')},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-is_favorite', 'created', 'title')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-is_favorite', 'title')},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, default='https://media.briantracy.com/blog/wp-content/uploads/2021/12/03083020/how-to-become-an-author.jpg', help_text='URL de la portada del libro', null=True),
        ),
    ]
