# Generated by Django 5.1.6 on 2025-03-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
    ]
