# Generated by Django 5.1.6 on 2025-03-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_is_favorite_to_tag'),
    ]

    operations = [
        # No operations - is_favorite field already added in migration 0007
    ] 