# Generated by Django 5.1.6 on 2025-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_is_favorite_to_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si la etiqueta está marcada como favorita'),
        ),
    ]
