# Generated by Django 5.1.6 on 2025-03-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_is_favorite_to_tag_only'),
    ]

    operations = [
        # No operations - is_favorite fields already added in migration 0007
    ]
