# Generated by Django 5.1.6 on 2025-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_is_favorite_to_tag_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si el autor está marcado como favorito'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si el libro está marcado como favorito'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Indica si la cita está marcada como favorita'),
        ),
    ]
