# Generated by Django 5.1.6 on 2025-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_is_favorite_to_remaining_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cached_cover_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas asociadas', related_name='quotes', through='api.QuoteTag', to='api.tag'),
        ),
    ]
