# Generated by Django 5.1.6 on 2025-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_cached_cover_path_book_cover_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cached_cover_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_cached',
            field=models.BooleanField(default=False),
        ),
    ]
