# Generated by Django 5.1.6 on 2025-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book_cached_cover_path_book_cover_cached_and_more'),
    ]

    operations = [
        # No operations - fields already added in 0012
    ]
