# Generated by Django 5.1.6 on 2025-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_cover_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cached_cover_path',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_cached',
        ),
    ]
