# Generated by Django 5.1.6 on 2025-03-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_book_gradient_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='gradient_primary_color',
            field=models.CharField(blank=True, help_text='Color primario para el gradiente de la etiqueta', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='gradient_secondary_color',
            field=models.CharField(blank=True, help_text='Color secundario para el gradiente de la etiqueta', max_length=7, null=True),
        ),
    ]
