# Generated by Django 5.1.6 on 2025-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book_url',
            field=models.URLField(blank=True, help_text='URL al libro en plataformas externas (Google Books, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='chapter',
            field=models.CharField(blank=True, help_text='Capítulo del libro al que pertenece la cita', max_length=200, null=True),
        ),
    ]
