# Generated by Django 5.1.6 on 2025-04-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_quote_book_url_quote_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido de la nota')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('is_private', models.BooleanField(default=False, help_text='Indica si la nota es privada o visible para otros usuarios')),
                ('quote', models.ForeignKey(help_text='Cita a la que pertenece la nota', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.quote')),
                ('user', models.ForeignKey(help_text='Usuario que creó la nota', on_delete=django.db.models.deletion.CASCADE, related_name='quote_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_notes',
                'ordering': ('created',),
            },
        ),
    ]
