# Generated by Django 5.1.6 on 2025-04-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_avatar_user_bio_user_github_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes_goal', models.PositiveIntegerField(default=100, help_text='Target number of quotes to collect')),
                ('books_goal', models.PositiveIntegerField(default=30, help_text='Target number of books to read')),
                ('authors_goal', models.PositiveIntegerField(default=20, help_text='Target number of authors to explore')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When these goals were created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When these goals were last updated')),
                ('user', models.OneToOneField(help_text='User who owns these goals', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Goals',
                'verbose_name_plural': 'User Goals',
                'db_table': 'user_goals',
            },
        ),
    ]
