# Generated by Django 5.1.6 on 2025-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_usergoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='duplicates_skipped',
            field=models.IntegerField(default=0, help_text='Número de duplicados omitidos'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='quotes_count',
            field=models.IntegerField(default=0, help_text='Número de citas importadas'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='platform',
            field=models.CharField(choices=[('kindle', 'Kindle'), ('google_books', 'Google Books'), ('apple_books', 'Apple Books'), ('google_books_batch', 'Google Books Batch')], help_text='Plataforma de origen', max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas asociadas', related_name='quotes', through='api.QuoteTag', to='api.tag'),
        ),
    ]
