# Generated by Django 5.1.6 on 2025-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_importlog_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas asociadas', related_name='quotes', through='api.QuoteTag', to='api.tag'),
        ),
    ]
