# Generated by Django 5.1.6 on 2025-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_quote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importlog',
            name='duplicates_skipped',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='quotes_count',
        ),
        migrations.AlterField(
            model_name='importlog',
            name='platform',
            field=models.CharField(choices=[('kindle', 'Kindle'), ('google_books', 'Google Books'), ('apple_books', 'Apple Books')], help_text='Plataforma de origen', max_length=50),
        ),
    ]
