# Generated by Django 5.1.6 on 2025-05-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_importlog_duplicates_skipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='platform',
            field=models.CharField(choices=[('kindle', 'Kindle'), ('google_books', 'Google Books'), ('google_books_batch', 'Google Books (Batch)'), ('apple_books', 'Apple Books')], help_text='Plataforma de origen', max_length=50),
        ),
    ]
