# Generated by Django 5.1.6 on 2025-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_importlog_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='duplicates_skipped',
            field=models.IntegerField(default=0, help_text='Número de citas duplicadas omitidas durante esta importación'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='quotes_added',
            field=models.IntegerField(default=0, help_text='Número de citas realmente añadidas durante esta importación'),
        ),
    ]
