# Generated by Django 5.1.6 on 2025-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_importlog_duplicates_skipped_importlog_quotes_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('reader', 'Reader'), ('scholar', 'Scholar')], default='free', max_length=10),
        ),
    ]
